// <auto-generated />
using System;
using AMIP.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AMIP.Infrastructure.Migrations
{
    [DbContext(typeof(AmipDbContext))]
    partial class AmipDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AMIP.Domain.Entities.Experiment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Conclusion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ParametersJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResultsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Experiments");
                });

            modelBuilder.Entity("AMIP.Domain.Entities.MarketCandle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Close")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CloseTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Exchange")
                        .HasColumnType("integer");

                    b.Property<decimal>("High")
                        .HasColumnType("numeric");

                    b.Property<int>("Interval")
                        .HasColumnType("integer");

                    b.Property<decimal>("Low")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Open")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("OpenTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Volume")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("Exchange", "Symbol", "Interval", "OpenTime")
                        .IsUnique();

                    b.ToTable("MarketCandles");
                });

            modelBuilder.Entity("AMIP.Domain.Entities.MarketFeature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FeatureDataJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("MarketFeatures");
                });

            modelBuilder.Entity("AMIP.Domain.Entities.MarketPattern", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ClusterId")
                        .HasColumnType("integer");

                    b.Property<string>("EmbeddingJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PatternId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("SuccessRate")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("MarketPatterns");
                });

            modelBuilder.Entity("AMIP.Domain.Entities.MarketRegime", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ModelVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Probability")
                        .HasColumnType("numeric");

                    b.Property<int>("RegimeLabel")
                        .HasColumnType("integer");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("MarketRegimes");
                });

            modelBuilder.Entity("AMIP.Domain.Entities.ModelMetrics", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Accuracy")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("EvaluatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("MaxDrawdown")
                        .HasColumnType("numeric");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Precision")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Recall")
                        .HasColumnType("numeric");

                    b.Property<decimal>("SharpeRatio")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("ModelMetrics");
                });

            modelBuilder.Entity("AMIP.Domain.Entities.ModelPrediction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("ActualResult")
                        .HasColumnType("integer");

                    b.Property<decimal>("Confidence")
                        .HasColumnType("numeric");

                    b.Property<int>("Direction")
                        .HasColumnType("integer");

                    b.Property<decimal>("DownProbability")
                        .HasColumnType("numeric");

                    b.Property<decimal>("NeutralProbability")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Risk")
                        .HasColumnType("numeric");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("UpProbability")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("ModelPredictions");
                });

            modelBuilder.Entity("AMIP.Domain.Entities.ModelRegistryEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ModelPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ModelRegistryEntries");
                });

            modelBuilder.Entity("AMIP.Domain.Entities.ProcessedCandle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsValidated")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MarketCandleId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("NormalizedClose")
                        .HasColumnType("numeric");

                    b.Property<decimal>("NormalizedHigh")
                        .HasColumnType("numeric");

                    b.Property<decimal>("NormalizedLow")
                        .HasColumnType("numeric");

                    b.Property<decimal>("NormalizedOpen")
                        .HasColumnType("numeric");

                    b.Property<decimal>("NormalizedVolume")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("ProcessedCandles");
                });
#pragma warning restore 612, 618
        }
    }
}
